# vim: set ft=yaml ts=2 expandtab:
---

name: CI
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      targeted_branch:
        type: string

jobs:

  selectbranch:
    uses: mafalb/workflows/.github/workflows/reusable-selectbranch.yml@prod
    with:
      targeted_branch: ${{ inputs.targeted_branch }}

  gpgkey:
    runs-on: ubuntu-latest
    steps:
      - name: Download gpgkey
        env:
          GPGKEY: https://cli.github.com/packages/githubcli-archive-keyring.gpg
          SHASUM: a5eb97c717ec3438bb94d465554e3560f8732403c28870780f779b8ab89975ea
          KEYID: 2C6106201985B60E6C7AC87323F3D4EA75716059
        run: curl -sO "$GPGKEY"
      - name: Check if key has changed
        run: | 
          gpg --show-keys $("$GPGKEY" | basename)
          gpg --show-keys $("$GPGKEY" | basename) | grep "$KEYID"
          cat $("$GPGKEY" | basename) | sha256sum
          cat $("$GPGKEY" | basename) | sha256sum | grep "$SHASUM" 
          
  ansiblecollection:
    needs: selectbranch
    uses: mafalb/workflows/.github/workflows/reusable-ansiblecollection.yml@prod
    with:
      targeted_branch: ${{ needs.selectbranch.outputs.ref }}

  molecule:

    runs-on: ubuntu-22.04
    needs: selectbranch
    strategy:
      fail-fast: false
      matrix:
        target:
          - fedora38
          - fedora39
          - fedora40
          - centos7
          - c8s
          - c9s
          - alma8
          - alma9
          - rocky8
          - rocky9
          - debian10
          - debian11
          - debian12
          - ubuntu18
          - ubuntu20
          - ubuntu22
          - ubuntu24
    env:
      CI_TARGET: ${{ matrix.target }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    steps:

      - name: Checkout workflows
        uses: actions/checkout@v4
        with:
          repository: mafalb/workflows
          path: workflows
          ref: ${{ needs.selectbranch.outputs.ref }}

      - name: Install Ansible
        uses: mafalb/workflows/.github/actions/installansible@prod
        with:
          extra_packages: 'molecule-plugins[podman],molecule'
          python_version: 3.11
          ansible_version: 2.16
          ref: dev  # FIX

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ansible_collections/mafalb/github

      - name: molecule default scenario
        working-directory: ansible_collections/mafalb/github
        run: |
          source ~/.virtualenvs/ansible/bin/activate
          molecule -c molecule/molecule.yml -e "molecule/env-$CI_TARGET.yml" test

  allsuccess:
    if: success() || failure()
    uses: mafalb/workflows/.github/workflows/reusable-allsuccess.yml@prod
    with:
      joblist: ${{ toJSON(needs) }}
    needs:
      - selectbranch
      - gpgkey
      - ansiblecollection
      - molecule
...
